### ISSUE TITLE
Official touch screen driver support

### ISSUE THREAD

**Issue by lawik** [nerves-project/nerves_system_rpi2#92]
### Environment

* Elixir version (`elixir -v`): any
* Nerves environment: (`mix nerves.env --info`)any
* Raspberry Pi 2

### Current behavior

The touch driver that is included in the rpi3 (but not in the rpi3a as noted in [this issue](https://github.com/nerves-project/nerves_system_rpi3a/issues/10) is missing in this system.

### Expected behavior

I think most people expect Scenic + Nerves to work out of the box beyond the pi3. So it would be neat if it did.

hassanshaikley on the slack is trying to get it working. I don't actually have a pi2 to test things on.

**Comment by GregMefford** [comment]
I have an rpi2 if you’d like me to confirm, @fhunleth

**Comment by fhunleth** [comment]
If it's easy for you to test out #93, that would help me a lot.

**Comment by hassanshaikley** [comment]
I tried to use it and it didn't work! But I'm not certain I did the right thing.

Steps I took: 

Added the following to deps:
```
      {:nerves_system_rpi2, "~> 1.8",
       github: "nerves-project/nerves_system_rpi2",
       branch: "enable-rpi-touchscreen",
       runtime: false,
       targets: :rpi2,
       nerves: [compile: true]}
````

Nuked `_build/`

ran `mix firmware`

ran `mix firmware.burn`

**Comment by fhunleth** [comment]
Do you have any hints as to what didn't work?

**Comment by hassanshaikley** [comment]
Ok I tried nuking the lockfile and now I'm seeing

```
  => Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.9.0/nerves_system_rpi2-portable-1.9.0-FF50FB1.tar.gz
     Status 404 Not Found
  => Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.9.0/nerves_system_rpi2-portable-1.9.0-FF50FB1E05532FB675002866732FB2911D722FBF3E7D837FAC49F8A7BCE7F57B.tar.gz
     Status 404 Not Found
```

So maybe what I tried didn't actually work because of some Mix stuff! I'll try to get this to work and update you with the result!

**Comment by hassanshaikley** [comment]
I realized the syntax in my `mix.exs` was wrong.. so I changed it to 

```
      {:nerves_system_rpi2,
       [
         github: "nerves-project/nerves_system_rpi2",
         branch: "enable-rpi-touchscreen",
         runtime: true,
         override: true,
         targets: :rpi2,
         compile: true,
         nerves: [compile: true]
       ]}
``` 
And it's still erroring with
```
Resolving Nerves artifacts...
  Resolving nerves_system_rpi2
  => Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.9.0/nerves_system_rpi2-portable-1.9.0-FF50FB1.tar.gz
     Status 404 Not Found
  => Trying https://github.com/nerves-project/nerves_system_rpi2/releases/download/v1.9.0/nerves_system_rpi2-portable-1.9.0-FF50FB1E05532FB675002866732FB2911D722FBF3E7D837FAC49F8A7BCE7F57B.tar.gz
     Status 404 Not Found
```

I don't know why it's looking for a release! I want to use the branch directly :/

**Comment by GregMefford** [comment]
I confirmed that it was working by downloading the source locally and running `mix nerves.artifact` in the source directory to build it on my machine so that it wouldn't try to fetch from GitHub Releases.

@mobileoverlord I think that the `nerves: [compile: true]` on the dependency should have caused it to compile locally if it can't fetch, right? Is that a bug we need to look into, or am I mis-remembering how that's supposed to work?

**Comment by fhunleth** [comment]
@hassanshaikley Are you able to get the touchscreen working now?

**Comment by hassanshaikley** [comment]
Oh I was going to wait for a release!

I could try and run it locally, but I've never done that before!

**Comment by fhunleth** [comment]
@hassanshaikley I will try to make it easy for you and keep my fingers crossed that the release I just made works: https://github.com/nerves-project/nerves_system_rpi2/releases/tag/v1.9.1

**Comment by hassanshaikley** [comment]
It works!
